### ISSUE TITLE
About a parameter in Bedtools

### ISSUE THREAD

**Issue by Jyyin333** [SysBioChalmers/ChIPexo_Pipeline#1]
hi ,Boerlin:
    the code you shared is gorgeous and very helpful.
    i have a question, i'm not totally understand the parameter(-fs) in bedtools genomecov although i have checked it in Bedtools guideline. In the bash file, you wrote: 
bedtools genomecov -ibam ${tmpPath}/${TF}_${i}.bam -fs 1
and  
bedtools genomecov -ibam ${tmpPath}/${TF}_${i}.bam -fs ${trim}
So i wonder what it does.
Thanks.

ps:
In combineReplicateWigFiles.py ,line 74.   The maxValue is not defined

**Comment by ChristophBoerlin** [comment]
Hej,
with the fs parameter one can set the length of the read that is going to be used. But in the first genomecov call we only want to get a coverage map of the first base of the read (therefore we use -fs 1). Otherwise the full 75bp of the read would be used. 

And thank you for pointing out the missing definition of maxValue, that is now fixed.
